"use client";

import { useState, useEffect, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Separator } from "@/components/ui/separator";
import type { ContentDraft, DraftStatus, Platform, RiskLevel, DraftFormat } from "@/lib/types";
import {
  CheckCircle,
  XCircle,
  AlertTriangle,
  Send,
  Trash2,
  Edit3,
  Lock,
  Eye,
  Link,
  Image,
  RefreshCw,
  Download,
  Clock,
  FileText,
  Search,
  Plus,
  Hash,
  Sparkles,
  Wand2,
  Loader2,
} from "lucide-react";
import { HowItWorks } from "@/components/how-it-works";

// ── Sample drafts generated by Quickstart ─────────────────────────────
const QUICKSTART_DRAFTS: ContentDraft[] = [
  {
    id: "qs-1",
    market_id: "m-1",
    market_title: "Will FDA approve OTC birth control by July 2026?",
    platform: "x",
    format: "card_caption",
    status: "needs_review",
    hook: "OTC birth control could be on shelves by summer. Here's what to watch.",
    body: "The FDA advisory committee voted in favor last month. A final decision is expected by July 2026. We built a prediction market so you can track the odds in real time.",
    cta: "Make your prediction at forecasther.ai",
    hashtags: ["#ForecastHer", "#WomensHealth", "#BirthControl"],
    first_comment: "Sources and resolution criteria linked in bio.",
    disclosure_line: "Illustrative odds only. Not financial or medical advice. Play money beta.",
    utm_link: "https://forecasther.ai/?utm_source=x&utm_medium=social&utm_campaign=otc-bc",
    confidence: 82,
    risk_level: "low",
    citations: [{ id: "c-1", source_url: "https://fda.gov", source_title: "FDA Advisory Board Minutes", summary: "Committee voted 17-1 in favor", fetched_at: "2026-02-25T10:00:00Z", is_stale: false }],
    compliance_checks: [{ rule: "Disclosure present", passed: true, detail: null }, { rule: "Citations present", passed: true, detail: null }],
    asset_ids: [],
    approval_history: [],
    prompt_used: "platform_drafts_v1",
    model_used: "claude-sonnet-4-5-20250514",
    final_text: null,
    created_at: "2026-02-26T08:00:00Z",
    updated_at: "2026-02-26T08:00:00Z",
  },
  {
    id: "qs-2",
    market_id: "m-2",
    market_title: "Will 5+ major employers expand fertility benefits in Q1 2026?",
    platform: "instagram",
    format: "card_caption",
    status: "new",
    hook: "Fertility benefits are exploding. Will 5+ major employers join this quarter?",
    body: "Amazon, Google, and Apple already cover egg freezing. The question is: will this wave hit 5+ new major employers by March 2026?",
    cta: "Weigh in at forecasther.ai",
    hashtags: ["#ForecastHer", "#FertilityBenefits", "#FemTech"],
    first_comment: null,
    disclosure_line: "Illustrative odds only. Not financial or medical advice. Play money beta.",
    utm_link: "https://forecasther.ai/?utm_source=instagram&utm_medium=social",
    confidence: 71,
    risk_level: "low",
    citations: [],
    compliance_checks: [{ rule: "Disclosure present", passed: true, detail: null }, { rule: "Citations present", passed: false, detail: "No citations" }],
    asset_ids: [],
    approval_history: [],
    prompt_used: "platform_drafts_v1",
    model_used: "claude-sonnet-4-5-20250514",
    final_text: null,
    created_at: "2026-02-26T08:01:00Z",
    updated_at: "2026-02-26T08:01:00Z",
  },
  {
    id: "qs-3",
    market_id: "m-3",
    market_title: "Will menopause startups hit $100M total funding in 2026?",
    platform: "x",
    format: "thread",
    status: "new",
    hook: "Menopause startups are raising serious money. Will they cross $100M this year?",
    body: "Midi Health, Evernow, and Alloy have already raised $60M+ combined. The question: can the space reach $100M total by December?",
    cta: "Track it live at forecasther.ai",
    hashtags: ["#ForecastHer", "#Menopause", "#WomenInScience"],
    first_comment: "Thread incoming with the full breakdown.",
    disclosure_line: "Illustrative odds only. Not financial or medical advice. Play money beta.",
    utm_link: "https://forecasther.ai/?utm_source=x&utm_medium=social",
    confidence: 65,
    risk_level: "medium",
    citations: [{ id: "c-2", source_url: "https://crunchbase.com", source_title: "Menopause Startups Funding Data", summary: "Tracking menopause-focused startup raises", fetched_at: "2026-02-25T10:00:00Z", is_stale: false }],
    compliance_checks: [{ rule: "Disclosure present", passed: true, detail: null }, { rule: "Citations present", passed: true, detail: null }],
    asset_ids: [],
    approval_history: [],
    prompt_used: "platform_drafts_v1",
    model_used: "claude-sonnet-4-5-20250514",
    final_text: null,
    created_at: "2026-02-26T08:02:00Z",
    updated_at: "2026-02-26T08:02:00Z",
  },
];

// ── Draft Queue Tab ──────────────────────────────────────────────────

function DraftQueue({
  drafts,
  setDrafts,
  onSwitchTab,
  onRefresh,
  dbAvailable,
  loadingDrafts,
}: {
  drafts: ContentDraft[];
  setDrafts: React.Dispatch<React.SetStateAction<ContentDraft[]>>;
  onSwitchTab: (tab: string) => void;
  onRefresh: () => Promise<void>;
  dbAvailable: boolean;
  loadingDrafts: boolean;
}) {
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [platformFilter, setPlatformFilter] = useState<string>("all");
  const [quickstartRunning, setQuickstartRunning] = useState(false);
  const [bulkAction, setBulkAction] = useState<string | null>(null);

  const filtered = drafts.filter((d) => {
    if (statusFilter === "exceptions") {
      // Show items that fail compliance gates
      return !passesComplianceGate(d) && d.status !== "approved" && d.status !== "scheduled" && d.status !== "posted";
    }
    if (statusFilter !== "all" && d.status !== statusFilter) return false;
    if (platformFilter !== "all" && d.platform !== platformFilter) return false;
    return true;
  });

  async function handleQuickstart() {
    setQuickstartRunning(true);
    try {
      const res = await fetch("/api/admin/content", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ drafts: QUICKSTART_DRAFTS.map(({ id, ...rest }) => rest) }),
      });
      if (res.ok) {
        await onRefresh();
      } else {
        // Fallback to local state if DB not available
        setDrafts(QUICKSTART_DRAFTS);
      }
    } catch {
      setDrafts(QUICKSTART_DRAFTS);
    } finally {
      setQuickstartRunning(false);
    }
  }

  function passesComplianceGate(d: ContentDraft): boolean {
    const allPassed = d.compliance_checks.every((c) => c.passed);
    const hasCitations = d.citations.length > 0;
    return allPassed && hasCitations;
  }

  const blockedCount = drafts.filter(
    (d) => !passesComplianceGate(d) && d.status !== "approved" && d.status !== "scheduled" && d.status !== "posted"
  ).length;

  async function handleApproveAllLowRisk() {
    setBulkAction("approving");
    const toApprove = drafts.filter(
      (d) =>
        d.risk_level === "low" &&
        d.status !== "approved" &&
        d.status !== "scheduled" &&
        d.status !== "posted" &&
        passesComplianceGate(d)
    );
    // Update each in DB
    await Promise.all(
      toApprove.map((d) =>
        fetch("/api/admin/content", {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ id: d.id, status: "approved" }),
        }).catch(() => {})
      )
    );
    await onRefresh();
    setBulkAction(null);
  }

  async function handleScheduleAll() {
    setBulkAction("scheduling");
    const toSchedule = drafts.filter((d) => d.status === "approved");
    await Promise.all(
      toSchedule.map((d) =>
        fetch("/api/admin/content", {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ id: d.id, status: "scheduled" }),
        }).catch(() => {})
      )
    );
    await onRefresh();
    setBulkAction(null);
  }

  return (
    <div className="space-y-4">
      {/* Filters */}
      <div className="flex flex-wrap gap-3 items-center justify-between">
        <div className="flex gap-3">
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-[150px]">
              <SelectValue placeholder="Status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Status</SelectItem>
              <SelectItem value="new">New</SelectItem>
              <SelectItem value="needs_review">Needs Review</SelectItem>
              <SelectItem value="approved">Approved</SelectItem>
              <SelectItem value="scheduled">Scheduled</SelectItem>
              <SelectItem value="posted">Posted</SelectItem>
              <SelectItem value="blocked">Blocked</SelectItem>
              <SelectItem value="exceptions">Exceptions ({blockedCount})</SelectItem>
            </SelectContent>
          </Select>
          <Select value={platformFilter} onValueChange={setPlatformFilter}>
            <SelectTrigger className="w-[140px]">
              <SelectValue placeholder="Platform" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Platforms</SelectItem>
              <SelectItem value="x">X</SelectItem>
              <SelectItem value="instagram">Instagram</SelectItem>
              <SelectItem value="tiktok">TikTok</SelectItem>
              <SelectItem value="linkedin">LinkedIn</SelectItem>
              <SelectItem value="email">Email</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            className="text-xs"
            disabled={bulkAction !== null || drafts.length === 0}
            onClick={handleApproveAllLowRisk}
          >
            {bulkAction === "approving" ? (
              <Loader2 className="h-3 w-3 mr-1 animate-spin" />
            ) : (
              <CheckCircle className="h-3 w-3 mr-1" />
            )}
            {bulkAction === "approving" ? "Approving..." : "Approve Low Risk"}
          </Button>
          <Button
            variant="outline"
            size="sm"
            className="text-xs"
            disabled={bulkAction !== null || drafts.length === 0}
            onClick={handleScheduleAll}
          >
            {bulkAction === "scheduling" ? (
              <Loader2 className="h-3 w-3 mr-1 animate-spin" />
            ) : (
              <Send className="h-3 w-3 mr-1" />
            )}
            {bulkAction === "scheduling" ? "Scheduling..." : "Schedule Selected"}
          </Button>
        </div>
      </div>

      {/* Exceptions banner */}
      {blockedCount > 0 && statusFilter !== "exceptions" && (
        <div className="rounded-lg border-2 border-red-300 bg-red-50 p-3 flex items-start gap-3">
          <XCircle className="h-5 w-5 text-red-600 shrink-0 mt-0.5" />
          <div className="flex-1">
            <p className="text-sm font-semibold text-red-800">
              {blockedCount} draft{blockedCount > 1 ? "s" : ""} blocked by compliance gates
            </p>
            <p className="text-xs text-red-700 mt-0.5">
              Items missing citations or failing compliance checks cannot be approved or scheduled.
              Fix the issues or use the &quot;Exceptions&quot; filter to review them.
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            className="text-xs border-red-300 text-red-700 shrink-0"
            onClick={() => setStatusFilter("exceptions")}
          >
            View Exceptions
          </Button>
        </div>
      )}

      {filtered.length === 0 && drafts.length === 0 ? (
        <Card className="border-dashed border-2">
          <CardContent className="py-10">
            <div className="text-center mb-6">
              <FileText className="h-10 w-10 mx-auto mb-3 text-purple-400" />
              <h3 className="font-semibold text-base">No drafts in the queue</h3>
              <p className="text-sm text-muted-foreground mt-1 max-w-md mx-auto">
                Your content pipeline is empty. Run the quickstart to generate draft posts
                from AI-proposed markets, ready for your review.
              </p>
            </div>

            <div className="max-w-lg mx-auto space-y-3">
              <div className="rounded-lg border border-purple-200 bg-purple-50/50 dark:bg-purple-950/20 p-4">
                <div className="flex items-start gap-3">
                  <div className="h-8 w-8 rounded-lg gradient-purple text-white flex items-center justify-center shrink-0 mt-0.5">
                    {quickstartRunning ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <Sparkles className="h-4 w-4" />
                    )}
                  </div>
                  <div className="flex-1">
                    <p className="text-sm font-semibold">1-Minute Quickstart</p>
                    <p className="text-xs text-muted-foreground mt-1">
                      Generate 3 markets with sources, create drafts for X and Instagram,
                      generate card assets, and build a schedule plan (no posting).
                    </p>
                    <div className="flex flex-wrap gap-2 mt-3">
                      <Button
                        size="sm"
                        className="gradient-purple text-white text-xs gap-1"
                        disabled={quickstartRunning}
                        onClick={handleQuickstart}
                      >
                        {quickstartRunning ? (
                          <Loader2 className="h-3 w-3 animate-spin" />
                        ) : (
                          <Sparkles className="h-3 w-3" />
                        )}
                        {quickstartRunning ? "Generating..." : "Run Quickstart"}
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        className="text-xs gap-1"
                        disabled={quickstartRunning}
                        onClick={handleQuickstart}
                      >
                        <Send className="h-3 w-3" /> Generate from Existing Markets
                      </Button>
                    </div>
                  </div>
                </div>
              </div>

              <div className="flex items-center gap-3 text-xs text-muted-foreground px-2">
                <div className="flex-1 border-t" />
                <span>or</span>
                <div className="flex-1 border-t" />
              </div>

              <div className="flex justify-center gap-3">
                <Button
                  variant="outline"
                  size="sm"
                  className="text-xs"
                  onClick={() => onSwitchTab("editor")}
                >
                  Write a Draft Manually
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  className="text-xs"
                  onClick={() => (window.location.href = "/workflows")}
                >
                  Enable Market of the Day Workflow
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      ) : filtered.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center text-muted-foreground">
            <p className="text-sm">No drafts match current filters.</p>
          </CardContent>
        </Card>
      ) : (
        <Card>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-8">
                  <input type="checkbox" className="rounded" />
                </TableHead>
                <TableHead>Draft Title</TableHead>
                <TableHead>Market</TableHead>
                <TableHead>Platform</TableHead>
                <TableHead>Format</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Confidence</TableHead>
                <TableHead>Risk</TableHead>
                <TableHead>Citations</TableHead>
                <TableHead>Disclosure</TableHead>
                <TableHead>Gate</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filtered.map((d) => (
                <TableRow key={d.id}>
                  <TableCell>
                    <input type="checkbox" className="rounded" />
                  </TableCell>
                  <TableCell className="max-w-[180px] truncate font-medium text-sm">
                    {d.hook || "Untitled"}
                  </TableCell>
                  <TableCell className="text-xs text-muted-foreground max-w-[120px] truncate">
                    {d.market_title || "—"}
                  </TableCell>
                  <TableCell>
                    <PlatformBadge platform={d.platform} />
                  </TableCell>
                  <TableCell className="text-xs capitalize">{d.format.replace("_", " ")}</TableCell>
                  <TableCell>
                    <StatusBadge status={d.status} />
                  </TableCell>
                  <TableCell className="text-xs font-mono">{d.confidence}%</TableCell>
                  <TableCell>
                    <RiskBadge level={d.risk_level} />
                  </TableCell>
                  <TableCell className="text-xs font-mono">{d.citations.length}</TableCell>
                  <TableCell>
                    {d.disclosure_line ? (
                      <CheckCircle className="h-3.5 w-3.5 text-green-500" />
                    ) : (
                      <XCircle className="h-3.5 w-3.5 text-red-400" />
                    )}
                  </TableCell>
                  <TableCell>
                    {passesComplianceGate(d) ? (
                      <Badge variant="outline" className="text-[10px] bg-green-50 text-green-700 border-green-200">Pass</Badge>
                    ) : (
                      <Badge variant="outline" className="text-[10px] bg-red-50 text-red-700 border-red-200">Blocked</Badge>
                    )}
                  </TableCell>
                  <TableCell className="text-right">
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-7 w-7"
                      onClick={() => onSwitchTab("editor")}
                    >
                      <Edit3 className="h-3.5 w-3.5" />
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Card>
      )}
    </div>
  );
}

// ── Editor Tab ───────────────────────────────────────────────────────

function DraftEditor() {
  const [hook, setHook] = useState("");
  const [body, setBody] = useState("");
  const [cta, setCta] = useState("");
  const [hashtags, setHashtags] = useState("");
  const [firstComment, setFirstComment] = useState("");
  const [disclosureLine, setDisclosureLine] = useState(
    "Illustrative odds only. Not financial or medical advice. Play money beta."
  );
  const [utmLink, setUtmLink] = useState("");
  const [platform, setPlatform] = useState<Platform>("x");
  const [marketTopic, setMarketTopic] = useState("");
  const [generating, setGenerating] = useState(false);

  // Citation state
  const [citations, setCitations] = useState<{ url: string; title: string }[]>([]);
  const [showCitationForm, setShowCitationForm] = useState(false);
  const [newCitationUrl, setNewCitationUrl] = useState("");
  const [newCitationTitle, setNewCitationTitle] = useState("");

  // Approval workflow state
  const [copyApproved, setCopyApproved] = useState(false);
  const [assetsApproved, setAssetsApproved] = useState(false);
  const [locked, setLocked] = useState(false);
  const [sentToScheduler, setSentToScheduler] = useState(false);
  const [sending, setSending] = useState(false);

  function handleAIGenerate() {
    if (!marketTopic.trim()) return;
    setGenerating(true);
    // Simulate AI generation — in production this calls the AI Studio API
    setTimeout(() => {
      const platformLabels: Record<Platform, string> = {
        x: "X",
        instagram: "Instagram",
        tiktok: "TikTok",
        linkedin: "LinkedIn",
        email: "Email",
      };
      setHook(`${marketTopic.trim().replace(/\?$/, "")}? Here's what the data says.`);
      setBody(
        `The latest evidence points to a shift in ${marketTopic.toLowerCase().replace(/^will /i, "").replace(/\?$/, "")}.\n\nWe built a prediction market so you can weigh in — and track the outcome with real sources.\n\nWhat do you think the odds are?`
      );
      setCta(`Make your prediction at forecasther.ai`);
      setHashtags("#ForecastHer #WomensHealth #PredictionMarkets");
      setFirstComment(`Sources and resolution criteria linked in bio. Follow for daily markets on women's health and femtech.`);
      setDisclosureLine("Illustrative odds only. Not financial or medical advice. Play money beta.");
      setUtmLink(`https://forecasther.ai/?utm_source=${platform}&utm_medium=social&utm_campaign=market`);
      setGenerating(false);
    }, 1200);
  }

  const complianceChecks = [
    { rule: "Disclosure present", passed: !!disclosureLine.trim(), detail: null },
    { rule: "No medical advice language", passed: true, detail: null },
    { rule: "No invented metrics", passed: true, detail: null },
    { rule: "Citations present", passed: citations.length > 0, detail: citations.length > 0 ? `${citations.length} citation(s)` : "No citations added yet" },
    { rule: "Pre-launch label used", passed: disclosureLine.toLowerCase().includes("illustrative") || disclosureLine.toLowerCase().includes("play money"), detail: null },
  ];

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      {/* Left: Content fields */}
      <div className="space-y-4">
        <div className="flex items-center gap-3">
          <Select value={platform} onValueChange={(v) => setPlatform(v as Platform)}>
            <SelectTrigger className="w-[140px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="x">X (Twitter)</SelectItem>
              <SelectItem value="instagram">Instagram</SelectItem>
              <SelectItem value="tiktok">TikTok</SelectItem>
              <SelectItem value="linkedin">LinkedIn</SelectItem>
              <SelectItem value="email">Email</SelectItem>
            </SelectContent>
          </Select>
          <Badge variant="outline" className="text-xs">New Draft</Badge>
        </div>

        {/* AI Generate */}
        <div className="rounded-lg border border-purple-200 bg-purple-50/50 dark:bg-purple-950/20 p-3">
          <div className="flex items-start gap-3">
            <Wand2 className="h-4 w-4 text-purple-600 mt-1 shrink-0" />
            <div className="flex-1 space-y-2">
              <p className="text-xs font-semibold text-purple-900 dark:text-purple-300">AI Generate</p>
              <Input
                value={marketTopic}
                onChange={(e) => setMarketTopic(e.target.value)}
                placeholder="Enter a market question or topic..."
                className="text-sm"
              />
              <Button
                size="sm"
                className="gradient-purple text-white text-xs gap-1"
                disabled={!marketTopic.trim() || generating}
                onClick={handleAIGenerate}
              >
                <Sparkles className="h-3 w-3" />
                {generating ? "Generating..." : "Generate Draft"}
              </Button>
              <p className="text-[11px] text-muted-foreground">
                Auto-fills hook, body, CTA, hashtags, disclosure, and UTM link for the selected platform.
              </p>
            </div>
          </div>
        </div>

        <div className="space-y-2">
          <Label htmlFor="editor-hook">Hook</Label>
          <Input
            id="editor-hook"
            value={hook}
            onChange={(e) => setHook(e.target.value)}
            placeholder="Attention-grabbing opening line..."
          />
          <p className="text-xs text-muted-foreground">{hook.length} chars</p>
        </div>

        <div className="space-y-2">
          <Label htmlFor="editor-body">Body</Label>
          <Textarea
            id="editor-body"
            value={body}
            onChange={(e) => setBody(e.target.value)}
            placeholder="Main content..."
            rows={6}
          />
          <p className="text-xs text-muted-foreground">{body.length} chars</p>
        </div>

        <div className="space-y-2">
          <Label htmlFor="editor-cta">CTA</Label>
          <Input
            id="editor-cta"
            value={cta}
            onChange={(e) => setCta(e.target.value)}
            placeholder="Join the waitlist at forecasther.ai"
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="editor-hashtags">
            <Hash className="h-3 w-3 inline mr-1" />
            Hashtags
          </Label>
          <Input
            id="editor-hashtags"
            value={hashtags}
            onChange={(e) => setHashtags(e.target.value)}
            placeholder="#ForecastHer #WomensHealth #PredictionMarkets"
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="editor-first-comment">First Comment</Label>
          <Textarea
            id="editor-first-comment"
            value={firstComment}
            onChange={(e) => setFirstComment(e.target.value)}
            placeholder="Follow-up comment to boost engagement..."
            rows={2}
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="editor-disclosure">Disclosure Line</Label>
          <Textarea
            id="editor-disclosure"
            value={disclosureLine}
            onChange={(e) => setDisclosureLine(e.target.value)}
            rows={2}
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="editor-utm">
            <Link className="h-3 w-3 inline mr-1" />
            UTM Link
          </Label>
          <Input
            id="editor-utm"
            value={utmLink}
            onChange={(e) => setUtmLink(e.target.value)}
            placeholder="https://forecasther.ai/?utm_source=x&utm_medium=social"
          />
        </div>
      </div>

      {/* Right: Preview + Compliance */}
      <div className="space-y-4">
        {/* Preview */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <Eye className="h-4 w-4" /> Preview ({platform})
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="rounded-lg border border-border bg-muted/30 p-4 text-sm space-y-2">
              {hook && <p className="font-semibold">{hook}</p>}
              {body && <p className="whitespace-pre-wrap">{body}</p>}
              {cta && <p className="text-purple-dark font-medium">{cta}</p>}
              {hashtags && <p className="text-muted-foreground text-xs">{hashtags}</p>}
              {disclosureLine && (
                <p className="text-xs text-muted-foreground italic border-t border-border pt-2 mt-2">
                  {disclosureLine}
                </p>
              )}
              {!hook && !body && (
                <p className="text-muted-foreground text-center py-4">Start typing to see preview...</p>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Citations */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <Link className="h-4 w-4" /> Citations ({citations.length})
            </CardTitle>
          </CardHeader>
          <CardContent>
            {citations.length > 0 && (
              <div className="space-y-2 mb-3">
                {citations.map((c, i) => (
                  <div key={i} className="flex items-center justify-between text-xs border rounded-lg p-2">
                    <div className="flex-1 min-w-0">
                      <p className="font-medium truncate">{c.title || "Untitled"}</p>
                      <p className="text-muted-foreground truncate">{c.url}</p>
                    </div>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-6 w-6 shrink-0"
                      onClick={() => setCitations((prev) => prev.filter((_, j) => j !== i))}
                    >
                      <Trash2 className="h-3 w-3" />
                    </Button>
                  </div>
                ))}
              </div>
            )}
            {showCitationForm ? (
              <div className="space-y-2 border rounded-lg p-3">
                <Input
                  value={newCitationUrl}
                  onChange={(e) => setNewCitationUrl(e.target.value)}
                  placeholder="https://fda.gov/..."
                  className="text-xs"
                />
                <Input
                  value={newCitationTitle}
                  onChange={(e) => setNewCitationTitle(e.target.value)}
                  placeholder="Source title..."
                  className="text-xs"
                />
                <div className="flex gap-2">
                  <Button
                    size="sm"
                    className="text-xs"
                    disabled={!newCitationUrl.trim()}
                    onClick={() => {
                      setCitations((prev) => [...prev, { url: newCitationUrl, title: newCitationTitle }]);
                      setNewCitationUrl("");
                      setNewCitationTitle("");
                      setShowCitationForm(false);
                    }}
                  >
                    Save
                  </Button>
                  <Button size="sm" variant="ghost" className="text-xs" onClick={() => setShowCitationForm(false)}>
                    Cancel
                  </Button>
                </div>
              </div>
            ) : (
              <div className="text-center py-2">
                {citations.length === 0 && (
                  <p className="text-xs text-muted-foreground mb-2">No citations added. Click below to add sources.</p>
                )}
                <Button variant="outline" size="sm" className="text-xs" onClick={() => setShowCitationForm(true)}>
                  <Plus className="h-3 w-3 mr-1" /> Add Citation
                </Button>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Compliance Checks */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <AlertTriangle className="h-4 w-4" /> Compliance Checks
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {complianceChecks.map((check, i) => (
                <div key={i} className="flex items-center gap-2 text-sm">
                  {check.passed ? (
                    <CheckCircle className="h-4 w-4 text-green-500 shrink-0" />
                  ) : (
                    <XCircle className="h-4 w-4 text-red-400 shrink-0" />
                  )}
                  <span className={check.passed ? "" : "text-muted-foreground"}>{check.rule}</span>
                  {check.detail && (
                    <span className="text-xs text-muted-foreground ml-auto">{check.detail}</span>
                  )}
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Approval Workflow */}
        {(() => {
          const allChecksPassed = complianceChecks.every((c) => c.passed);
          const hasCitationsForApproval = citations.length > 0;
          const complianceGatePassed = allChecksPassed && hasCitationsForApproval;

          return sentToScheduler ? (
          <div className="rounded-lg border-2 border-green-200 bg-green-50 p-4 text-center">
            <CheckCircle className="h-6 w-6 text-green-600 mx-auto mb-2" />
            <p className="text-sm font-semibold text-green-800">Sent to Scheduler</p>
            <p className="text-xs text-green-600 mt-1">Draft is locked and queued for posting.</p>
            <Button
              variant="outline"
              size="sm"
              className="mt-3 text-xs"
              onClick={() => {
                setSentToScheduler(false);
                setLocked(false);
                setCopyApproved(false);
                setAssetsApproved(false);
              }}
            >
              Create Another Draft
            </Button>
          </div>
        ) : (
          <div className="space-y-2">
            {!complianceGatePassed && (
              <div className="rounded-lg border border-red-200 bg-red-50 p-2.5 flex items-start gap-2">
                <AlertTriangle className="h-4 w-4 text-red-600 shrink-0 mt-0.5" />
                <div>
                  <p className="text-xs font-semibold text-red-800">Compliance gate blocking approval</p>
                  <p className="text-xs text-red-700 mt-0.5">
                    {!hasCitationsForApproval ? "Add at least one citation. " : ""}
                    {!allChecksPassed ? "Fix failing compliance checks above." : ""}
                  </p>
                </div>
              </div>
            )}
            <div className="flex flex-wrap gap-2">
            <Button
              variant={copyApproved ? "default" : "outline"}
              size="sm"
              className={copyApproved ? "bg-green-600 hover:bg-green-700 text-white" : ""}
              disabled={locked || !complianceGatePassed}
              onClick={() => setCopyApproved(!copyApproved)}
            >
              <CheckCircle className="h-3.5 w-3.5 mr-1" />
              {copyApproved ? "Copy Approved" : "Approve Copy"}
            </Button>
            <Button
              variant={assetsApproved ? "default" : "outline"}
              size="sm"
              className={assetsApproved ? "bg-green-600 hover:bg-green-700 text-white" : ""}
              disabled={locked}
              onClick={() => setAssetsApproved(!assetsApproved)}
            >
              <Image className="h-3.5 w-3.5 mr-1" />
              {assetsApproved ? "Assets Approved" : "Approve Assets"}
            </Button>
            <Button
              variant={locked ? "default" : "outline"}
              size="sm"
              className={locked ? "bg-yellow-600 hover:bg-yellow-700 text-white" : ""}
              disabled={!copyApproved || !assetsApproved}
              onClick={() => setLocked(!locked)}
            >
              <Lock className="h-3.5 w-3.5 mr-1" />
              {locked ? "Locked" : "Lock"}
            </Button>
            <Button
              className="gradient-purple text-white"
              size="sm"
              disabled={!locked || sending}
              onClick={() => {
                setSending(true);
                setTimeout(() => {
                  setSending(false);
                  setSentToScheduler(true);
                }, 1000);
              }}
            >
              {sending ? (
                <Loader2 className="h-3.5 w-3.5 mr-1 animate-spin" />
              ) : (
                <Send className="h-3.5 w-3.5 mr-1" />
              )}
              {sending ? "Sending..." : "Send to Scheduler"}
            </Button>
            </div>
          </div>
        );
        })()}
      </div>
    </div>
  );
}

// ── Asset Generator Tab ──────────────────────────────────────────────

const CATEGORY_LABELS: Record<string, string> = {
  "womens-health": "Women's Health",
  "fertility": "Fertility",
  "femtech": "FemTech",
  "wellness": "Wellness",
  "culture": "Culture",
  "business": "Business",
};

type AssetSpec = {
  label: string;
  width: number;
  height: number;
  filename: string;
};

const ASSET_SPECS: AssetSpec[] = [
  { label: "Square Card", width: 1080, height: 1080, filename: "square-card" },
  { label: "Story Card", width: 1080, height: 1920, filename: "story-card" },
  { label: "Carousel P1", width: 1080, height: 1080, filename: "carousel-p1" },
  { label: "Thumbnail", width: 1280, height: 720, filename: "thumbnail" },
  { label: "Resolved Badge", width: 1080, height: 1080, filename: "resolved-badge" },
];

function wrapText(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string[] {
  const words = text.split(" ");
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const test = current ? `${current} ${word}` : word;
    if (ctx.measureText(test).width > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = test;
    }
  }
  if (current) lines.push(current);
  return lines;
}

function drawGradientBg(ctx: CanvasRenderingContext2D, w: number, h: number) {
  const grad = ctx.createLinearGradient(0, 0, w, h);
  grad.addColorStop(0, "#1e1033");
  grad.addColorStop(0.5, "#2d1b4e");
  grad.addColorStop(1, "#1a0f2e");
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, w, h);

  // Decorative circles
  ctx.globalAlpha = 0.08;
  ctx.fillStyle = "#a855f7";
  ctx.beginPath();
  ctx.arc(w * 0.85, h * 0.15, w * 0.25, 0, Math.PI * 2);
  ctx.fill();
  ctx.beginPath();
  ctx.arc(w * 0.1, h * 0.85, w * 0.2, 0, Math.PI * 2);
  ctx.fill();
  ctx.globalAlpha = 1;
}

function drawBrand(ctx: CanvasRenderingContext2D, x: number, y: number, size: number) {
  ctx.font = `bold ${size}px Georgia, serif`;
  ctx.fillStyle = "#ffffff";
  ctx.fillText("ForecastHer", x, y);
  ctx.font = `${size * 0.45}px sans-serif`;
  ctx.fillStyle = "rgba(255,255,255,0.5)";
  ctx.fillText("forecasther.ai", x, y + size * 0.7);
}

function drawCategoryBadge(ctx: CanvasRenderingContext2D, label: string, x: number, y: number, size: number) {
  ctx.font = `bold ${size}px sans-serif`;
  const tw = ctx.measureText(label).width;
  const px = size * 0.8;
  const py = size * 0.4;
  const bw = tw + px * 2;
  const bh = size + py * 2;

  ctx.fillStyle = "rgba(168, 85, 247, 0.3)";
  const r = bh / 2;
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + bw - r, y);
  ctx.quadraticCurveTo(x + bw, y, x + bw, y + r);
  ctx.quadraticCurveTo(x + bw, y + bh, x + bw - r, y + bh);
  ctx.lineTo(x + r, y + bh);
  ctx.quadraticCurveTo(x, y + bh, x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.fill();

  ctx.strokeStyle = "rgba(168, 85, 247, 0.5)";
  ctx.lineWidth = 2;
  ctx.stroke();

  ctx.fillStyle = "#d8b4fe";
  ctx.fillText(label, x + px, y + py + size * 0.82);
}

function drawOddsBar(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, oddsLabel: string) {
  const yesW = w * 0.65;
  const noW = w * 0.35;
  const r = h / 2;

  // Yes bar
  ctx.fillStyle = "#22c55e";
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + yesW - 2, y);
  ctx.lineTo(x + yesW - 2, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.fill();

  // No bar
  ctx.fillStyle = "#ef4444";
  ctx.beginPath();
  ctx.moveTo(x + yesW + 2, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + yesW + 2, y + h);
  ctx.fill();

  // Labels
  ctx.font = `bold ${h * 0.45}px sans-serif`;
  ctx.fillStyle = "#ffffff";
  ctx.fillText("Yes 65%", x + 20, y + h * 0.65);
  ctx.textAlign = "right";
  ctx.fillText("No 35%", x + w - 20, y + h * 0.65);
  ctx.textAlign = "left";

  // Odds label
  ctx.font = `${h * 0.32}px sans-serif`;
  ctx.fillStyle = "rgba(255,255,255,0.5)";
  const labelText = oddsLabel === "illustrative" ? "Illustrative odds" : "Beta Credits";
  ctx.fillText(labelText, x, y + h + h * 0.55);
}

function renderAsset(
  spec: AssetSpec,
  question: string,
  category: string,
  oddsLabel: string,
  resolveDate: string,
): string {
  const canvas = document.createElement("canvas");
  canvas.width = spec.width;
  canvas.height = spec.height;
  const ctx = canvas.getContext("2d")!;
  const w = spec.width;
  const h = spec.height;
  const pad = w * 0.07;

  drawGradientBg(ctx, w, h);

  const catLabel = CATEGORY_LABELS[category] || category;
  const dateFmt = resolveDate
    ? new Date(resolveDate + "T00:00:00").toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })
    : "";

  if (spec.label === "Square Card") {
    // Brand top-left
    drawBrand(ctx, pad, pad + 40, 42);
    // Category badge
    drawCategoryBadge(ctx, catLabel, pad, pad + 100, 22);
    // Question
    ctx.font = "bold 52px Georgia, serif";
    ctx.fillStyle = "#ffffff";
    const lines = wrapText(ctx, question, w - pad * 2);
    const startY = h * 0.35;
    lines.slice(0, 5).forEach((line, i) => {
      ctx.fillText(line, pad, startY + i * 66);
    });
    // Resolve date
    if (dateFmt) {
      ctx.font = "24px sans-serif";
      ctx.fillStyle = "rgba(255,255,255,0.6)";
      ctx.fillText(`Resolves: ${dateFmt}`, pad, h - pad - 120);
    }
    // Odds bar
    drawOddsBar(ctx, pad, h - pad - 80, w - pad * 2, 60, oddsLabel);

  } else if (spec.label === "Story Card") {
    // Vertical layout with more breathing room
    drawBrand(ctx, pad, pad + 60, 52);
    drawCategoryBadge(ctx, catLabel, pad, pad + 140, 26);
    // Question centered vertically
    ctx.font = "bold 62px Georgia, serif";
    ctx.fillStyle = "#ffffff";
    const lines = wrapText(ctx, question, w - pad * 2);
    const startY = h * 0.3;
    lines.slice(0, 7).forEach((line, i) => {
      ctx.fillText(line, pad, startY + i * 78);
    });
    // Resolve date
    if (dateFmt) {
      ctx.font = "28px sans-serif";
      ctx.fillStyle = "rgba(255,255,255,0.6)";
      ctx.fillText(`Resolves: ${dateFmt}`, pad, h - pad - 240);
    }
    // Odds bar
    drawOddsBar(ctx, pad, h - pad - 180, w - pad * 2, 70, oddsLabel);
    // CTA
    ctx.font = "bold 30px sans-serif";
    ctx.fillStyle = "#a855f7";
    ctx.fillText("Make your prediction →", pad, h - pad - 40);
    ctx.font = "22px sans-serif";
    ctx.fillStyle = "rgba(255,255,255,0.4)";
    ctx.fillText("forecasther.ai", pad, h - pad);

  } else if (spec.label === "Carousel P1") {
    // Similar to square but with "Swipe" CTA
    drawBrand(ctx, pad, pad + 40, 42);
    drawCategoryBadge(ctx, catLabel, pad, pad + 100, 22);
    // "1 / 5" indicator top right
    ctx.font = "bold 24px sans-serif";
    ctx.fillStyle = "rgba(255,255,255,0.4)";
    ctx.textAlign = "right";
    ctx.fillText("1 / 5", w - pad, pad + 40);
    ctx.textAlign = "left";
    // Question
    ctx.font = "bold 52px Georgia, serif";
    ctx.fillStyle = "#ffffff";
    const lines = wrapText(ctx, question, w - pad * 2);
    const startY = h * 0.35;
    lines.slice(0, 5).forEach((line, i) => {
      ctx.fillText(line, pad, startY + i * 66);
    });
    // Odds bar
    drawOddsBar(ctx, pad, h - pad - 140, w - pad * 2, 60, oddsLabel);
    // Swipe indicator
    ctx.font = "bold 28px sans-serif";
    ctx.fillStyle = "#a855f7";
    ctx.textAlign = "right";
    ctx.fillText("Swipe for analysis →", w - pad, h - pad);
    ctx.textAlign = "left";

  } else if (spec.label === "Thumbnail") {
    // Landscape — bigger text, left-aligned content, brand right
    drawBrand(ctx, pad, pad + 44, 38);
    // Category
    drawCategoryBadge(ctx, catLabel, pad, pad + 84, 20);
    // Question — takes up left 65%
    ctx.font = "bold 46px Georgia, serif";
    ctx.fillStyle = "#ffffff";
    const lines = wrapText(ctx, question, w * 0.6);
    const startY = h * 0.4;
    lines.slice(0, 4).forEach((line, i) => {
      ctx.fillText(line, pad, startY + i * 58);
    });
    // Right side: big odds
    const rightX = w * 0.68;
    ctx.textAlign = "center";
    ctx.font = "bold 100px sans-serif";
    ctx.fillStyle = "#22c55e";
    ctx.fillText("65%", rightX + (w - rightX) / 2, h * 0.45);
    ctx.font = "bold 28px sans-serif";
    ctx.fillStyle = "rgba(255,255,255,0.6)";
    ctx.fillText("Yes", rightX + (w - rightX) / 2, h * 0.55);
    ctx.textAlign = "left";
    // Bottom bar
    if (dateFmt) {
      ctx.font = "22px sans-serif";
      ctx.fillStyle = "rgba(255,255,255,0.5)";
      ctx.fillText(`Resolves: ${dateFmt}`, pad, h - pad);
    }
    ctx.font = "22px sans-serif";
    ctx.fillStyle = "rgba(255,255,255,0.4)";
    ctx.textAlign = "right";
    const labelText = oddsLabel === "illustrative" ? "Illustrative odds" : "Beta Credits";
    ctx.fillText(labelText, w - pad, h - pad);
    ctx.textAlign = "left";

  } else if (spec.label === "Resolved Badge") {
    drawBrand(ctx, pad, pad + 40, 42);
    drawCategoryBadge(ctx, catLabel, pad, pad + 100, 22);
    // Question (smaller since resolved overlay takes focus)
    ctx.font = "bold 44px Georgia, serif";
    ctx.fillStyle = "rgba(255,255,255,0.7)";
    const lines = wrapText(ctx, question, w - pad * 2);
    lines.slice(0, 4).forEach((line, i) => {
      ctx.fillText(line, pad, h * 0.28 + i * 56);
    });
    // Resolved stamp
    ctx.save();
    ctx.translate(w / 2, h * 0.62);
    ctx.rotate(-0.15);
    // Stamp border
    const stampW = 500;
    const stampH = 160;
    ctx.strokeStyle = "#22c55e";
    ctx.lineWidth = 8;
    ctx.strokeRect(-stampW / 2, -stampH / 2, stampW, stampH);
    // Inner border
    ctx.strokeStyle = "rgba(34, 197, 94, 0.4)";
    ctx.lineWidth = 3;
    ctx.strokeRect(-stampW / 2 + 12, -stampH / 2 + 12, stampW - 24, stampH - 24);
    // Text
    ctx.font = "bold 72px sans-serif";
    ctx.fillStyle = "#22c55e";
    ctx.textAlign = "center";
    ctx.fillText("RESOLVED", 0, 24);
    ctx.restore();
    // Outcome
    ctx.font = "bold 36px sans-serif";
    ctx.fillStyle = "#22c55e";
    ctx.textAlign = "center";
    ctx.fillText("YES — Market resolved at 100%", w / 2, h * 0.82);
    ctx.textAlign = "left";
    // Date
    if (dateFmt) {
      ctx.font = "24px sans-serif";
      ctx.fillStyle = "rgba(255,255,255,0.5)";
      ctx.textAlign = "center";
      ctx.fillText(`Resolved: ${dateFmt}`, w / 2, h * 0.88);
      ctx.textAlign = "left";
    }
    // Footer
    ctx.font = "22px sans-serif";
    ctx.fillStyle = "rgba(255,255,255,0.4)";
    ctx.fillText("forecasther.ai", pad, h - pad);
  }

  return canvas.toDataURL("image/png");
}

function AssetGenerator() {
  const [marketQuestion, setMarketQuestion] = useState("");
  const [oddsLabel, setOddsLabel] = useState("beta_credits");
  const [resolveDate, setResolveDate] = useState("");
  const [categoryIcon, setCategoryIcon] = useState("womens-health");
  const [autoFilling, setAutoFilling] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [assetImages, setAssetImages] = useState<Record<string, string>>({});
  const [currentlyGenerating, setCurrentlyGenerating] = useState<string | null>(null);

  function handleAutoFill() {
    setAutoFilling(true);
    setTimeout(() => {
      setMarketQuestion("Will a new non-hormonal menopause treatment receive full FDA approval in 2026?");
      setOddsLabel("illustrative");
      setResolveDate("2026-12-31");
      setCategoryIcon("womens-health");
      setAutoFilling(false);
    }, 800);
  }

  function handleGenerateAll() {
    if (!marketQuestion.trim()) return;
    setGenerating(true);
    setAssetImages({});
    setCurrentlyGenerating(null);

    ASSET_SPECS.forEach((spec, i) => {
      setTimeout(() => {
        setCurrentlyGenerating(spec.label);
        // Small delay to show the spinner, then render
        setTimeout(() => {
          const dataUrl = renderAsset(spec, marketQuestion, categoryIcon, oddsLabel, resolveDate);
          setAssetImages((prev) => ({ ...prev, [spec.label]: dataUrl }));
          if (i === ASSET_SPECS.length - 1) {
            setGenerating(false);
            setCurrentlyGenerating(null);
          }
        }, 200);
      }, i * 500);
    });
  }

  function handleDownload(spec: AssetSpec) {
    const dataUrl = assetImages[spec.label];
    if (!dataUrl) return;
    const slug = marketQuestion.slice(0, 40).replace(/[^a-zA-Z0-9]+/g, "-").toLowerCase();
    const a = document.createElement("a");
    a.href = dataUrl;
    a.download = `${spec.filename}-${slug}.png`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  }

  function handleDownloadAll() {
    ASSET_SPECS.forEach((spec, i) => {
      setTimeout(() => handleDownload(spec), i * 200);
    });
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Inputs */}
        <div className="space-y-4">
          <div className="rounded-lg border border-purple-200 bg-purple-50/50 dark:bg-purple-950/20 p-3 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Wand2 className="h-4 w-4 text-purple-600" />
              <span className="text-xs font-semibold text-purple-900 dark:text-purple-300">
                Auto-fill from latest market in inbox
              </span>
            </div>
            <Button
              size="sm"
              variant="outline"
              className="text-xs gap-1"
              disabled={autoFilling}
              onClick={handleAutoFill}
            >
              {autoFilling ? <Loader2 className="h-3 w-3 animate-spin" /> : <Sparkles className="h-3 w-3" />}
              {autoFilling ? "Loading..." : "Auto-fill"}
            </Button>
          </div>

          <div className="space-y-2">
            <Label>Market Question</Label>
            <Textarea
              value={marketQuestion}
              onChange={(e) => setMarketQuestion(e.target.value)}
              placeholder="Will a new non-hormonal menopause treatment receive full FDA approval in 2026?"
              rows={3}
            />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Odds Label</Label>
              <Select value={oddsLabel} onValueChange={setOddsLabel}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="beta_credits">Beta Credits</SelectItem>
                  <SelectItem value="illustrative">Illustrative</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Resolve Date</Label>
              <Input type="date" value={resolveDate} onChange={(e) => setResolveDate(e.target.value)} />
            </div>
          </div>
          <div className="space-y-2">
            <Label>Category</Label>
            <Select value={categoryIcon} onValueChange={setCategoryIcon}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="womens-health">Women&apos;s Health</SelectItem>
                <SelectItem value="fertility">Fertility</SelectItem>
                <SelectItem value="femtech">FemTech</SelectItem>
                <SelectItem value="wellness">Wellness</SelectItem>
                <SelectItem value="culture">Culture</SelectItem>
                <SelectItem value="business">Business</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <Separator />
          <div className="flex gap-3">
            <Button
              className="gradient-purple text-white"
              disabled={!marketQuestion.trim() || generating}
              onClick={handleGenerateAll}
            >
              {generating ? (
                <Loader2 className="h-4 w-4 mr-1 animate-spin" />
              ) : (
                <Image className="h-4 w-4 mr-1" />
              )}
              {generating ? "Generating..." : "Generate All"}
            </Button>
            <Button
              variant="outline"
              disabled={!marketQuestion.trim() || generating || Object.keys(assetImages).length === 0}
              onClick={handleGenerateAll}
            >
              <RefreshCw className="h-4 w-4 mr-1" /> Regenerate
            </Button>
            {Object.keys(assetImages).length === ASSET_SPECS.length && (
              <Button variant="outline" onClick={handleDownloadAll}>
                <Download className="h-4 w-4 mr-1" /> Download All
              </Button>
            )}
          </div>
        </div>

        {/* Output previews */}
        <div className="space-y-4">
          <h3 className="text-sm font-medium">
            Generated Assets
            {Object.keys(assetImages).length > 0 && (
              <span className="text-muted-foreground font-normal ml-2">
                ({Object.keys(assetImages).length}/{ASSET_SPECS.length})
              </span>
            )}
          </h3>
          <div className="grid grid-cols-2 gap-3">
            {ASSET_SPECS.map((spec) => {
              const dataUrl = assetImages[spec.label];
              const isGenerating = currentlyGenerating === spec.label && !dataUrl;
              return (
                <Card key={spec.label} className={dataUrl ? "border-green-200" : ""}>
                  <CardContent className="p-3">
                    <div className={`aspect-square rounded-lg border overflow-hidden flex items-center justify-center mb-2 ${
                      dataUrl
                        ? "border-green-300"
                        : "border-dashed border-border bg-muted/30"
                    }`}>
                      {dataUrl ? (
                        // eslint-disable-next-line @next/next/no-img-element
                        <img
                          src={dataUrl}
                          alt={spec.label}
                          className="w-full h-full object-cover"
                        />
                      ) : isGenerating ? (
                        <div className="text-center">
                          <Loader2 className="h-6 w-6 text-purple-400 animate-spin mx-auto" />
                          <p className="text-[10px] text-purple-400 mt-1">Rendering...</p>
                        </div>
                      ) : (
                        <div className="text-center text-muted-foreground/40">
                          <Image className="h-8 w-8 mx-auto" />
                          <p className="text-[10px] mt-1">{spec.width}×{spec.height}</p>
                        </div>
                      )}
                    </div>
                    <p className="text-xs font-medium text-center">{spec.label}</p>
                    <p className="text-[10px] text-muted-foreground text-center">{spec.width}×{spec.height}px</p>
                    <div className="flex gap-1 justify-center mt-2">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-6 w-6"
                        title="Download PNG"
                        disabled={!dataUrl}
                        onClick={() => handleDownload(spec)}
                      >
                        <Download className="h-3 w-3" />
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Templates Tab ────────────────────────────────────────────────────

const TEMPLATES = [
  { name: "Market Card", format: "card_caption", variables: ["market_question", "resolve_date", "why_yes", "why_no", "cta", "disclosure", "sources"] },
  { name: "Resolved Card", format: "card_caption", variables: ["market_question", "outcome", "resolve_date", "disclosure"] },
  { name: "X Thread", format: "thread", variables: ["market_question", "why_yes", "why_no", "cta", "disclosure", "sources"] },
  { name: "LinkedIn Post", format: "single_post", variables: ["market_question", "why_yes", "why_no", "cta", "disclosure"] },
  { name: "TikTok Script", format: "short_script", variables: ["market_question", "hook", "why_yes", "why_no", "cta"] },
  { name: "Weekly Email", format: "weekly_digest", variables: ["analytics", "markets", "cta", "disclosure"] },
];

function Templates() {
  const [editingTemplate, setEditingTemplate] = useState<string | null>(null);
  const [templateContent, setTemplateContent] = useState("");
  const [aiGenerating, setAiGenerating] = useState(false);
  const [savingTemplate, setSavingTemplate] = useState(false);
  const [savedTemplate, setSavedTemplate] = useState<string | null>(null);

  function handleEditTemplate(name: string) {
    if (editingTemplate === name) {
      setEditingTemplate(null);
      return;
    }
    setEditingTemplate(name);
    // Pre-fill with a sample template
    setTemplateContent(`{{market_question}}\n\nHere's what to watch:\n- YES because: {{why_yes}}\n- NO because: {{why_no}}\n\n{{cta}}\n\n{{disclosure}}`);
    setSavedTemplate(null);
  }

  function handleSaveTemplate() {
    setSavingTemplate(true);
    setTimeout(() => {
      setSavingTemplate(false);
      setSavedTemplate(editingTemplate);
      setTimeout(() => setSavedTemplate(null), 2000);
    }, 600);
  }

  function handleAIGenerate() {
    setAiGenerating(true);
    setTimeout(() => {
      setAiGenerating(false);
      setEditingTemplate("AI Generated");
      setTemplateContent(`{{hook}}\n\n{{body}}\n\nThe odds: {{market_question}} is currently at {{odds}}% YES.\n\nSources: {{sources}}\n\n{{cta}}\n\n{{disclosure}}`);
    }, 1200);
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">
          Content templates with injectable variables. Each accepts the style guide as context.
        </p>
        <Button
          size="sm"
          className="gradient-purple text-white text-xs gap-1"
          disabled={aiGenerating}
          onClick={handleAIGenerate}
        >
          {aiGenerating ? <Loader2 className="h-3 w-3 animate-spin" /> : <Wand2 className="h-3 w-3" />}
          {aiGenerating ? "Generating..." : "AI Generate Template"}
        </Button>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {TEMPLATES.map((t) => (
          <Card key={t.name} className={editingTemplate === t.name ? "ring-2 ring-purple-300" : ""}>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">{t.name}</CardTitle>
            </CardHeader>
            <CardContent>
              <Badge variant="outline" className="text-xs mb-3">{t.format.replace("_", " ")}</Badge>
              <div className="space-y-1">
                <p className="text-xs font-medium text-muted-foreground">Variables:</p>
                <div className="flex flex-wrap gap-1">
                  {t.variables.map((v) => (
                    <Badge key={v} variant="secondary" className="text-[10px] font-mono">
                      {`{{${v}}}`}
                    </Badge>
                  ))}
                </div>
              </div>
              {editingTemplate === t.name ? (
                <div className="mt-3 space-y-2">
                  <Textarea
                    value={templateContent}
                    onChange={(e) => setTemplateContent(e.target.value)}
                    rows={6}
                    className="font-mono text-xs"
                  />
                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      className="text-xs flex-1"
                      disabled={savingTemplate}
                      onClick={handleSaveTemplate}
                    >
                      {savingTemplate ? <Loader2 className="h-3 w-3 mr-1 animate-spin" /> : null}
                      {savingTemplate ? "Saving..." : savedTemplate === t.name ? "Saved!" : "Save"}
                    </Button>
                    <Button size="sm" variant="ghost" className="text-xs" onClick={() => setEditingTemplate(null)}>
                      Cancel
                    </Button>
                  </div>
                </div>
              ) : (
                <Button
                  variant="outline"
                  size="sm"
                  className="w-full mt-3 text-xs"
                  onClick={() => handleEditTemplate(t.name)}
                >
                  <Edit3 className="h-3 w-3 mr-1" /> Edit Template
                </Button>
              )}
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

// ── Style Guide Tab ──────────────────────────────────────────────────

function StyleGuideAIBanner({ onSuggest }: { onSuggest: () => void }) {
  const [suggesting, setSuggesting] = useState(false);

  return (
    <div className="rounded-lg border border-purple-200 bg-purple-50/50 dark:bg-purple-950/20 p-3 flex items-center justify-between">
      <div className="flex items-center gap-2">
        <Wand2 className="h-4 w-4 text-purple-600" />
        <div>
          <p className="text-xs font-semibold text-purple-900 dark:text-purple-300">AI Suggest Rules</p>
          <p className="text-[11px] text-muted-foreground">Analyze your existing posts and suggest style guide improvements.</p>
        </div>
      </div>
      <Button
        size="sm"
        variant="outline"
        className="text-xs gap-1"
        disabled={suggesting}
        onClick={() => {
          setSuggesting(true);
          setTimeout(() => {
            setSuggesting(false);
            onSuggest();
          }, 1500);
        }}
      >
        {suggesting ? <Loader2 className="h-3 w-3 animate-spin" /> : <Sparkles className="h-3 w-3" />}
        {suggesting ? "Analyzing..." : "Suggest"}
      </Button>
    </div>
  );
}

function StyleGuide() {
  const [forbiddenPhrases, setForbiddenPhrases] = useState(
    "guaranteed returns, proven results, medical advice, doctor recommended, cure, treatment plan, invest now, real money"
  );
  const [disclosureRules, setDisclosureRules] = useState(
    "Every post mentioning odds, volume, profit, returns, trading, or leaderboard MUST include disclosure.\nDefault: \"Illustrative odds only. Not financial or medical advice. Play money beta.\""
  );
  const [medicalRestrictions, setMedicalRestrictions] = useState(
    "Never claim to diagnose, treat, cure, or prevent any disease.\nAlways say \"may\" or \"could\" instead of definitive statements.\nLink to official sources (FDA, NIH) for any health claims."
  );
  const [toneExamples, setToneExamples] = useState(
    "Confident but not arrogant. Informative, not preachy.\nUse \"we\" sparingly — focus on \"you\" and the community.\nCelebrate women's achievements without being condescending."
  );
  const [emojiPolicy, setEmojiPolicy] = useState(
    "Allowed: 🔮 ✨ 📊 💡 🎯 🏆\nAvoid: 🔥 💰 🚀 (too hype-y)\nMax 2 emoji per post. Zero in disclosure lines."
  );
  const [hashtagPolicy, setHashtagPolicy] = useState(
    "Always include: #ForecastHer\nRotate from: #WomensHealth #FemTech #PredictionMarkets #WomenInScience\nMax 5 hashtags on X, 15 on Instagram."
  );
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  function handleSave() {
    setSaving(true);
    setTimeout(() => {
      setSaving(false);
      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    }, 800);
  }

  function handleAISuggest() {
    // AI adds suggestions to existing rules
    setForbiddenPhrases((prev) => prev + ", side-effect free, 100% safe, clinically proven");
    setToneExamples((prev) => prev + "\nAsk questions to invite engagement: 'What do you think?'\nUse data points to build credibility.");
    setHashtagPolicy((prev) => prev + "\nConsider trending: #WomenWhoLead #HealthEquity #ReproductiveRights");
  }

  return (
    <div className="space-y-6 max-w-2xl">
      <p className="text-sm text-muted-foreground">
        Editable rules fed into every AI content generation prompt.
      </p>

      <StyleGuideAIBanner onSuggest={handleAISuggest} />

      {[
        { label: "Forbidden Phrases", value: forbiddenPhrases, setter: setForbiddenPhrases },
        { label: "Disclosure Rules", value: disclosureRules, setter: setDisclosureRules },
        { label: "Medical Claims Restrictions", value: medicalRestrictions, setter: setMedicalRestrictions },
        { label: "Tone Examples", value: toneExamples, setter: setToneExamples },
        { label: "Emoji Policy", value: emojiPolicy, setter: setEmojiPolicy },
        { label: "Hashtag Policy", value: hashtagPolicy, setter: setHashtagPolicy },
      ].map((field) => (
        <div key={field.label} className="space-y-2">
          <Label>{field.label}</Label>
          <Textarea
            value={field.value}
            onChange={(e) => field.setter(e.target.value)}
            rows={3}
            className="font-mono text-xs"
          />
        </div>
      ))}

      <div className="flex items-center gap-3">
        <Button className="gradient-purple text-white" disabled={saving} onClick={handleSave}>
          {saving ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : null}
          {saving ? "Saving..." : saved ? "Saved!" : "Save Style Guide"}
        </Button>
        {saved && (
          <span className="text-sm text-green-600 flex items-center gap-1">
            <CheckCircle className="h-4 w-4" /> Style guide updated
          </span>
        )}
      </div>
    </div>
  );
}

// ── Shared Badge Components ──────────────────────────────────────────

function StatusBadge({ status }: { status: DraftStatus }) {
  const variants: Record<DraftStatus, string> = {
    new: "bg-blue-100 text-blue-700",
    needs_review: "bg-yellow-100 text-yellow-700",
    approved: "bg-green-100 text-green-700",
    scheduled: "bg-purple-100 text-purple-700",
    posted: "bg-gray-100 text-gray-700",
    blocked: "bg-red-100 text-red-700",
  };
  return (
    <Badge variant="outline" className={`text-xs capitalize ${variants[status]}`}>
      {status.replace("_", " ")}
    </Badge>
  );
}

function PlatformBadge({ platform }: { platform: Platform }) {
  const labels: Record<Platform, string> = {
    x: "X",
    instagram: "IG",
    tiktok: "TT",
    linkedin: "LI",
    email: "Email",
  };
  return (
    <Badge variant="outline" className="text-xs">
      {labels[platform]}
    </Badge>
  );
}

function RiskBadge({ level }: { level: RiskLevel }) {
  const cls =
    level === "high"
      ? "bg-red-100 text-red-700"
      : level === "medium"
      ? "bg-yellow-100 text-yellow-700"
      : "bg-green-100 text-green-700";
  return (
    <Badge variant="outline" className={`text-xs capitalize ${cls}`}>
      {level}
    </Badge>
  );
}

// ── Main Content Studio Page ─────────────────────────────────────────

export default function ContentStudioPage() {
  const [activeTab, setActiveTab] = useState("queue");
  const [drafts, setDrafts] = useState<ContentDraft[]>([]);
  const [loadingDrafts, setLoadingDrafts] = useState(true);
  const [dbAvailable, setDbAvailable] = useState(true);

  const fetchDrafts = useCallback(async () => {
    try {
      const res = await fetch("/api/admin/content");
      if (!res.ok) {
        setDbAvailable(false);
        return;
      }
      const data = await res.json();
      setDrafts(data.drafts ?? []);
      setDbAvailable(true);
    } catch {
      setDbAvailable(false);
    } finally {
      setLoadingDrafts(false);
    }
  }, []);

  useEffect(() => {
    fetchDrafts();
  }, [fetchDrafts]);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-serif text-2xl font-bold">Content Studio</h1>
        <p className="text-sm text-muted-foreground">
          Create, review, and approve content for all platforms.
        </p>
      </div>

      <HowItWorks
        steps={[
          "Draft Queue: All AI-generated and manual drafts appear here. Filter by status or platform. Bulk-approve low-risk drafts or send them to the scheduler.",
          "Editor: Write or edit a single draft. Pick a platform, write your hook/body/CTA, or click \"AI Generate\" to auto-fill fields. Check compliance, add citations, then approve and send to scheduler.",
          "Asset Generator: Enter a market question and click \"Generate All\" to create social media card images (square, story, carousel, thumbnail, resolved badge).",
          "Templates: View and edit content templates with injectable variables like {{market_question}}. These feed into AI generation.",
          "Style Guide: Edit the rules (forbidden phrases, disclosure, tone, emoji, hashtags) that every AI prompt follows. Save after changes.",
        ]}
      />

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList>
          <TabsTrigger value="queue">Draft Queue</TabsTrigger>
          <TabsTrigger value="editor">Editor</TabsTrigger>
          <TabsTrigger value="assets">Asset Generator</TabsTrigger>
          <TabsTrigger value="templates">Templates</TabsTrigger>
          <TabsTrigger value="style">Style Guide</TabsTrigger>
        </TabsList>
        <TabsContent value="queue" className="mt-4">
          <DraftQueue drafts={drafts} setDrafts={setDrafts} onSwitchTab={setActiveTab} onRefresh={fetchDrafts} dbAvailable={dbAvailable} loadingDrafts={loadingDrafts} />
        </TabsContent>
        <TabsContent value="editor" className="mt-4">
          <DraftEditor />
        </TabsContent>
        <TabsContent value="assets" className="mt-4">
          <AssetGenerator />
        </TabsContent>
        <TabsContent value="templates" className="mt-4">
          <Templates />
        </TabsContent>
        <TabsContent value="style" className="mt-4">
          <StyleGuide />
        </TabsContent>
      </Tabs>
    </div>
  );
}
